apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-custom
  namespace: ignashov
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-custom
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: nginx-custom
    spec:
      containers:
      - name: nginx-custom-index
        image: imsolty/nginx-custom-index:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          protocol: TCP
