apiVersion: batch/v1
kind: Job
metadata:
  name: create-directory
  namespace: ignashov
spec:
  template:
    spec:
      containers:
      - name: create-dir
        image: busybox
        command: ['sh', '-c', 'mkdir -p /mnt/redis-data']
      restartPolicy: Never